USE NEWDATA;
CREATE TABLE TABLE2
(
	HOTEN VARCHAR(50),
	TUOI INT,
	LOP INT,
	CHECK (TUOI > 0)
);
INSERT TABLE2 (HOTEN, TUOI)
VALUES ('LAN LAN', 18);
INSERT TABLE2 (HOTEN, TUOI)
VALUES ('DIEP DIEP', 20);

SELECT * FROM TABLE2;

UPDATE TABLE2 SET LOP = 9 WHERE TUOI = 18;
UPDATE TABLE2 SET LOP = 9 WHERE TUOI = 20;

SELECT DISTINCT LOP, TUOI, HOTEN FROM TABLE2;
UPDATE TABLE2 SET LOP = 10 WHERE  tuoi = 20;
alter table table2 add studentID int identity (100, 1);
SET IDENTITY_INSERT TABLE2 off;
INSERT TABLE2(HOTEN, TUOI, LOP, STUDENTid) VALUES ('XUAN XUAN', 19, 11, 104);
INSERT TABLE2 VALUES ('thu thu', 18, 5, 'hue');
SELECT DISTINCT LOP, TUOI, HOTEN FROM TABLE2;
INSERT TABLE2 VALUES ('hoa hoa', 21, 6, 'hanoi');
SELECT DISTINCT LOP, TUOI, HOTEN FROM TABLE2;

ALTER TABLE TABLE2 ALTER COLUMN HOTEN NVARCHAR(50);
ALTER TABLE TABLE2 ADD DIACHI NVARCHAR(50);
ALTER TABLE TABLE2 ALTER COLUMN HOTEN VARCHAR(50);
ALTER TABLE TABLE2 ALTER COLUMN DIACHI VARCHAR(50);

sp_rename table3, table2;
sp_rename 'table2.hoVAten', 'hoten', 'column';

CREATE TABLE table4(ngaysinh DATE);

BEGIN TRAN;
TRUNCATE TABLE TABLE2;
ROLLBACK;

SELECT * FROM TABLE2;

use QUANLY;
select nv.TenNV as TEN, sum(cts.TongTien) as Tongsale from ChiTietSale cts
inner join NhanVien nv
on nv.NhanVienID = cts.NhanVienID
group by nv.TenNV
order by sum(cts.TongTien) desc;


use NEWDATA;



INSERT TABLE2 VALUES('NHI_UYEN', 24, 15, '%UE');
UPDATE TABLE2 SET HOTEN = '_XUAN LAN' WHERE TUOI = 24;

ALTER TABLE TABLE2 ADD NAMSINH DATE;

SELECT * FROM TABLE1;
SELECT * FROM TABLE2;

ALTER TABLE TABLE1 ADD STUDENTID INT IDENTITY (101, 1);
ALTER TABLE TABLE1 ADD NAMSINH INT, CHECK (NAMSINH > 1996);
UPDATE TABLE1 SET NAMSINH = 1997 WHERE STUDENTID = 101;
INSERT TABLE1 VALUES(3, 2007);
INSERT TABLE1 VALUES(4, 2005);
INSERT TABLE1 VALUES(5, 2008);
INSERT TABLE1 VALUES(6, 2001);
INSERT TABLE1 
VALUES(7, 2009),
(8, 2010);
-- UPDATE TABLE2 SET TABLE2.NAMSINH = (SELECT TABLE1.NAMSINH FROM TABLE1 WHERE table2.studentID = TABLE1.STUDENTID);
SELECT COUNT(*) FROM TABLE1 WHERE STUDENTid >=102;


USE QUANLY;

SELECT CTS.NhanVienID, COUNT(*) AS [SỐ KHÁCH HÀNG] FROM ChiTietSale CTS
GROUP BY CTS.NhanVienID
HAVING COUNT(*) <= 2;


SELECT TOP (2) WITH TIES HoNV, TenNV, NV.GioiTinh, NV.NhanVienID 
FROM NhanVien NV
WHERE GioiTinh = 'NAM'
ORDER BY NV.HONV;

USE NEWDATA;
DELETE TOP (2) FROM TABLE1

SELECT * FROM TABLE1;
SELECT * FROM TABLE2;

SELECT T1.STUDENTid, T1.STT FROM TABLE1 T1
UNION
SELECT T2.studentID, T2.TUOI
FROM TABLE2 T2
ORDER BY 2;

CREATE PROC SPTABLE1
@STT INT,
@NAMSINH INT
AS
BEGIN
INSERT TABLE1 VALUES (@STT, @NAMSINH)
END

EXEC SPTABLE1 8, 2012;
EXEC SPTABLE1 12, 2020;