CREATE DATABASE KIEMTRASQL;
USE KIEMTRASQL;

CREATE TABLE NHACUNGCAP
(
	MANHACC INT IDENTITY PRIMARY KEY,
	TENNHACC VARCHAR(50),
	DIACHI VARCHAR(50),
	SODT INT,
	MASOTHUE VARCHAR(50)
);

ALTER TABLE DANGKYCUNGCAP
DROP CONSTRAINT FK_DKCC1;

TRUNCATE TABLE DANGKYCUNGCAP;
CREATE TABLE LOAIDICHVU
(
	MALOAIDV INT PRIMARY KEY IDENTITY,
	TENLOAIDV VARCHAR(50)
);

CREATE TABLE MUCPHI 
(
	MAMP INT PRIMARY KEY IDENTITY,
	DONGIA INT,
	MOTA VARCHAR(50),
	CHECK (DONGIA > 0)
);

CREATE TABLE DONGXE
(
	DONGXE VARCHAR(50) PRIMARY KEY,
	HANGXE VARCHAR(50),
	SOCHONGOI INT,
	CHECK (SOCHONGOI > 0)
);

CREATE TABLE DANGKYCUNGCAP
(
	MADKCC INT PRIMARY KEY IDENTITY,
	MANHACC INT,
	MALOAIDV INT,
	DONGXE VARCHAR(50),
	MAMP INT,
	NGAYBATDAUCUNGCAP DATE,
	NGAYKETTHUCUNGCAP DATE,
	SOLUONGXEDANGKY INT,
	CHECK (SOLUONGXEDANGKY > 0)
);

ALTER TABLE DANGKYCUNGCAP 
ADD CONSTRAINT FK_DKCC1
FOREIGN KEY (MANHACC) REFERENCES NHACUNGCAP(MANHACC);

ALTER TABLE DANGKYCUNGCAP 
ADD CONSTRAINT FK_DKCC2
FOREIGN KEY (MALOAIDV) REFERENCES LOAIDICHVU(MALOAIDV);

ALTER TABLE DANGKYCUNGCAP 
ADD CONSTRAINT FK_DKCC3
FOREIGN KEY (MAMP) REFERENCES MUCPHI(MAMP);

ALTER TABLE DANGKYCUNGCAP 
ADD CONSTRAINT FK_DKCC4
FOREIGN KEY (DONGXE) REFERENCES DONGXE(DONGXE);

SELECT * FROM nhacungcap;

ALTER TABLE NHACUNGCAP ALTER COLUMN SODT VARCHAR(50);

INSERT NHACUNGCAP(TENNHACC, DIACHI, SODT, MASOTHUE) VALUES ('Cty TNHH Toan Phap', 'Hai Chau', 05113999888, '568941');

INSERT NHACUNGCAP(TENNHACC, DIACHI, SODT, MASOTHUE) VALUES ('Cty Co phan Dong Du', 'Lien Chieu', 05113999880, '456789');

INSERT NHACUNGCAP(TENNHACC, DIACHI, SODT, MASOTHUE) VALUES ('Ong Nguyen Van A', 'Hoa Thuan', 05113999890, '456790');

INSERT NHACUNGCAP(TENNHACC, DIACHI, SODT, MASOTHUE) VALUES ('Cong ty co phan Toan Cau Xanh', 'Hai Chau', 05113658945, 546546);


CREATE PROCEDURE PS_NHACUNGCAP
@TENNHACC VARCHAR(50),
@DIACHI VARCHAR(50),
@SODT VARCHAR(50), 
@MASOTHUE VARCHAR(50)
AS
BEGIN
INSERT NHACUNGCAP(TENNHACC, DIACHI, SODT, MASOTHUE) 
VALUES (@TENNHACC, @DIACHI, @SODT, @MASOTHUE)
END;
EXECUTE PS_NHACUNGCAP 'Cty TNHH AMA', 'Thanh Khe', 05113875466, 54672345;
EXECUTE PS_NHACUNGCAP 'Ba Tran Thi Bich Van', 'Lien Chien', 05113875465, 546345;
EXECUTE PS_NHACUNGCAP 'Cty TNHH Phan Thanh', 'Thanh Khe', 05113875469, 546344;
EXECUTE PS_NHACUNGCAP 'Cty Phan Dinh Nam', 'Hoa Thuan', 05113875470, 546349;
EXECUTE PS_NHACUNGCAP 'Tap Doan Dong Nam A', 'Lien Chieu', 05113875470, 546349;
EXECUTE PS_NHACUNGCAP 'Cty co phan Rang Dong', 'Lien Chieu', 05113875477, 546350;

SELECT * FROM NHACUNGCAP;
UPDATE NHACUNGCAP SET MASOTHUE = 546723 WHERE DIACHI = 'Thanh Khe';

INSERT LOAIDICHVU (TENLOAIDV) VALUES ('Dich vu xe taxi');

INSERT LOAIDICHVU (TENLOAIDV) VALUES ('Dich vu xe car');


INSERT MUCPHI (DONGIA, MOTA) VALUES (10000, 'Ap dung tu 1/2015');

INSERT DONGXE (DONGXE, HANGXE, SOCHONGOI) VALUES ('Hiace', 'Toyota', 16);

SELECT * FROM MUCPHI;

UPDATE MUCPHI SET DONGIA = 15000, MOTA = 'Ap dung tu 2/2015' WHERE MAMP = 2;

INSERT DANGKYCUNGCAP (MANHACC, MALOAIDV, DONGXE, MAMP, NGAYBATDAUCUNGCAP, NGAYKETTHUCUNGCAP, SOLUONGXEDANGKY)
VALUES (5, 1, 'Hiace', 1, '20151120', '20161120', 4);

CREATE TABLE TESTTABLE
(
	MaTable VARCHAR(50)
);


DECLARE @i INT = 0;
DECLARE @MaTable VARCHAR(50);

WHILE @i < 10

BEGIN
SET @MaTable = CONCAT('NCC',@i);
INSERT TESTTABLE(MATABLE) VALUES (@MaTable);
SET @i = @i + 1;
END;


SELECT * FROM TESTTABLE;