// <auto-generated />
using BoDeTracNghiemDemo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BoDeTracNghiemDemo.Migrations
{
    [DbContext(typeof(AppDataContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.CauHoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CauTraLoi1");

                    b.Property<string>("CauTraLoi2");

                    b.Property<string>("CauTraLoi3");

                    b.Property<string>("CauTraLoi4");

                    b.Property<string>("Ten");

                    b.Property<int>("TheLoaiId");

                    b.HasKey("Id");

                    b.HasIndex("TheLoaiId");

                    b.ToTable("CauHoi");
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.CauHoiThi", b =>
                {
                    b.Property<int>("CauHoiId");

                    b.Property<int>("ThiId");

                    b.Property<string>("Ten")
                        .IsRequired();

                    b.HasKey("CauHoiId", "ThiId");

                    b.HasIndex("ThiId");

                    b.ToTable("CauHoiThis");
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.DapAn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CauHoiId");

                    b.Property<string>("Ten");

                    b.HasKey("Id");

                    b.HasIndex("CauHoiId")
                        .IsUnique();

                    b.ToTable("DapAns");
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.Diem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ten");

                    b.Property<int>("ThiId");

                    b.HasKey("Id");

                    b.HasIndex("ThiId")
                        .IsUnique();

                    b.ToTable("Diems");
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("MatKhau")
                        .IsRequired();

                    b.Property<string>("Ten")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.TheLoai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ten");

                    b.HasKey("Id");

                    b.ToTable("TheLoais");
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.Thi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CauHoiThiId");

                    b.Property<int>("NguoiDungId");

                    b.Property<string>("Ten")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("This");
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.CauHoi", b =>
                {
                    b.HasOne("BoDeTracNghiemDemo.Models.TheLoai", "TheLoai")
                        .WithMany("CauHois")
                        .HasForeignKey("TheLoaiId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.CauHoiThi", b =>
                {
                    b.HasOne("BoDeTracNghiemDemo.Models.CauHoi", "CauHoi")
                        .WithMany("CauHoiThis")
                        .HasForeignKey("CauHoiId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BoDeTracNghiemDemo.Models.Thi", "Thi")
                        .WithMany("CauHoiThis")
                        .HasForeignKey("ThiId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.DapAn", b =>
                {
                    b.HasOne("BoDeTracNghiemDemo.Models.CauHoi", "CauHoi")
                        .WithOne("DapAn")
                        .HasForeignKey("BoDeTracNghiemDemo.Models.DapAn", "CauHoiId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.Diem", b =>
                {
                    b.HasOne("BoDeTracNghiemDemo.Models.Thi", "Thi")
                        .WithOne("Diem")
                        .HasForeignKey("BoDeTracNghiemDemo.Models.Diem", "ThiId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.Thi", b =>
                {
                    b.HasOne("BoDeTracNghiemDemo.Models.NguoiDung", "NguoiDung")
                        .WithMany("This")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
